[package]
name = "coursework"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gio = "0.14.0"

[dependencies.gtk]
version = "0.14.0"
features = ["v3_24"]

